function [DATI]=C_dati(test)
if test=='Test1'
        DATI= struct(  'name',  test,...
        'domain',           [0,1;0,1],...
        'exact_sol',        'sin(pi.*x).*exp(y)',...
        'force',            'pi*pi*sin(pi.*x).*exp(y)',...
        'grad_exact_1',     'pi*cos(pi.*x).*exp(x.*y)',...
        'grad_exact_2',     'sin(pi.*x).*exp(y)',...
        'alpha',             1,...
        'beta',              1,...        
        'fem',              'P1',...         % Q1 - P1
        'nqn_1D',            4,...           % (1,2,3,4,5,6,.....)
        'nqn_2D',            3,...          % (1,3,4,7,10,16,64)
        'MeshType',         'TS', ...        % ['TS' 'TU' 'QS' 'QU']
        'refinement_vector', [2,3,4,5],...   % [0,1,2,3,4,5,6,7,....]
        'visual_graph',      'Y',...
        'print_out',         'Y',...
        'plot_errors',       'Y');
end

if test=='Test2'
        DATI= struct(  'name',  test,...
        'domain',           [0,1;0,1],...
        'exact_sol',        'sin(pi.*x).*exp(y)',...
        'force',            'pi*pi*sin(pi.*x).*exp(y)',...
        'grad_exact_1',     'pi*cos(pi.*x).*exp(x.*y)',...
        'grad_exact_2',     'sin(pi.*x).*exp(y)',...
        'alpha',             1,...
        'beta',              1,...        
        'fem',              'P1',...         % Q1 - P1
        'nqn_1D',            4,...           % (1,2,3,4,5,6,.....)
        'nqn_2D',            3,...          % (1,3,4,7,10,16,64)
        'MeshType',         'TS', ...        % ['TS' 'TU' 'QS' 'QU']
        'refinement_vector', [2,3,4,5],...   % [0,1,2,3,4,5,6,7,....]
        'visual_graph',      'N',...
        'print_out',         'Y',...
        'plot_errors',       'Y');
end

