function [Matrices]=C_build_out_matrices(A,b,M,P,u_g)
%% function [Matrices]=C_build_out_matrices(A,b,M,P,u_g)
%============================================================================
% Store matrices and vector in the struct Matrices
%============================================================================

Matrices = struct('A',A,...
                'b',b,...
                'M',M,...
                'P',P,...
                'u_g',u_g);