function [DATI]=C_dati(test)

if (test == 'Test1')
    DATI= struct(  'name',  test,...
        'domain',           [0,1;0,1],...
        'exact_sol',        '2*atan(pi*x).*exp(2*y)',...
        'force',            '(4*pi^3*x.*(1+pi^2*x.^2).^(-2) - 8*atan(pi*x)).*exp(2*y)',...
        'grad_exact_1',     '(2*pi/(1+pi^2*x.^2)).*exp(2*y)',...
        'grad_exact_2',     '4*atan(pi*x).*exp(2*y)',...
        'fem',              'P1',...         % Q1 - P1
        'nqn_1D',            4,...           % (1,2,3,4,5,6,.....)
        'nqn_2D',            3,...          % (1,3,4,7,10,16,64)
        'MeshType',         'TS', ...        % ['TS' 'TU' 'QS' 'QU']
        'refinement_vector', [3,4,5,6],...   % [0,1,2,3,4,5,6,7,....]
        'visual_graph',      'Y',...
        'print_out',         'Y',...
        'plot_errors',       'Y');  
end
 

