function [DATI]=C_dati(test)

if test=='Test1'
    DATI= struct(  'name',  test,...
        'domain',           [0,1;0,1],...
        'exact_sol',        '(1-x.*x).*sin(2*pi.*y)',...
        'force',            'sin(2*pi.*y).*(4+4*pi*pi-2.*x.*x)',...
        'grad_exact_1',     '-2*x.*sin(2*pi.*y)',...
        'grad_exact_2',     '2*pi*(1-x.*x).*cos(2*pi.*y)',...
        'alpha',             1,...
        'beta',              2,...        
        'fem',              'P1',...         % Q1 - P1
        'nqn_1D',            4,...           % (1,2,3,4,5,6,.....)
        'nqn_2D',            3,...          % (1,3,4,7,10,16,64)
        'MeshType',         'TS', ...        % ['TS' 'TU' 'QS' 'QU']
        'refinement_vector', [3,4,5,6],...   % [0,1,2,3,4,5,6,7,....]
        'visual_graph',      'Y',...
        'print_out',         'Y',...
        'plot_errors',       'Y');

elseif test=='Test2'
        DATI= struct(  'name',  test,...
        'domain',           [0,1;0,1],...
        'exact_sol',        '(1-x.*x).*sin(2*pi.*y)',...
        'force',            'sin(2*pi.*y).*(4+4*pi*pi-2.*x.*x)',...
        'grad_exact_1',     '-2*x.*sin(2*pi.*y)',...
        'grad_exact_2',     '2*pi*(1-x.*x).*cos(2*pi.*y)',...
        'alpha',             1,...
        'beta',              2,...         
        'fem',              'P1',...         % Q1 - P1
        'nqn_1D',            4,...           % (1,2,3,4,5,6,.....)
        'nqn_2D',            3,...          % (1,3,4,7,10,16,64)
        'MeshType',         'TS', ...        % ['TS' 'TU' 'QS' 'QU']
        'refinement_vector', [3,4,5,6],...   % [0,1,2,3,4,5,6,7,....]
        'visual_graph',      'N',...
        'print_out',         'Y',...
        'plot_errors',       'Y');
end

 

