
function [DATI]=C_dati(test)

if (test == 'Test1')
    DATI= struct( 'name',  test,...
        'domain',           [-1,2;0,1],...
        'exact_sol',        '2*x.*cos(2*pi*x).*sin(2*pi*y)',...
        'force',            'sin(2*pi*y).*(4*pi.*sin(pi*x)+10*pi*pi.*x.*cos(pi*x))',...
        'grad_exact_1',     'sin(2*pi*y).*(2*cos(pi*x)-2*pi.*x.*sin(pi*x))',...
        'grad_exact_2',     '4*pi*cos(2*pi*y).*x.*cos(pi*x)',...
        'fem',              'P1',...         % Q1 - P1
        'nqn_1D',            4,...           % (1,2,3,4,5,6,.....)
        'nqn_2D',            3,...          % (1,3,4,7,10,16,64)
        'MeshType',         'TS', ...        % ['TS' 'TU' 'QS' 'QU']
        'refinement_vector', [3,4,5,6],...   % [0,1,2,3,4,5,6,7,....]
        'visual_graph',      'Y',...
        'print_out',         'Y',...
        'plot_errors',       'Y');
    
elseif (test == 'Test2')
    DATI= struct(  'name',  test,...
        'domain',           [-1,2;0,1],...
        'exact_sol',        '2*x.*cos(2*pi*x).*sin(2*pi*y)',...
        'force',            'sin(2*pi*y).*(4*pi.*sin(pi*x)+10*pi*pi.*x.*cos(pi*x))',...
        'grad_exact_1',     'sin(2*pi*y).*(2*cos(pi*x)-2*pi.*x.*sin(pi*x))',...
        'grad_exact_2',     '4*pi*cos(2*pi*y).*x.*cos(pi*x)',...
        'fem',              'P1',...         % Q1 - P1
        'nqn_1D',            4,...           % (1,2,3,4,5,6,.....)
        'nqn_2D',            3,...          % (1,3,4,7,10,16,64)
        'MeshType',         'TS', ...        % ['TS' 'TU' 'QS' 'QU']
        'refinement_vector', [3,4,5,6],...   % [0,1,2,3,4,5,6,7,....]
        'visual_graph',      'N',...
        'print_out',         'Y',...
        'plot_errors',       'Y');    
end
 

