function [DATI]=C_dati(test)

if test=='Test1'
    DATI= struct(  'name',  test,...
        'domain',           [0,1; 0,1],...
        'exact_sol',        '',...
        'force',            '',...
        'grad_exact_1',     '',...
        'grad_exact_2',     '',...
        'alpha',            ,...
        'beta',             ,...        
        'fem',              'P1',...         % Q1 - P1
        'nqn_1D',            4,...           % (1,2,3,4,5,6,.....)
        'nqn_2D',            3,...          % (1,3,4,7,10,16,64)
        'MeshType',         'TS', ...        % ['TS' 'TU' 'QS' 'QU']
        'refinement_vector', [3,4,5,6],...   % [0,1,2,3,4,5,6,7,....]
        'stabilization',    'N',...         % ['N', 'Y']
        'visual_graph',      'Y',...
        'print_out',         'Y',...
        'plot_errors',       'Y');
end

