function [DATI]=C_dati(test)

if test=='Test1'
    DATI= struct(  'name',  test,...
        'domain',           [0,1;0,1],...
        'exact_sol',        'exp(x.*y)',...
        'force',            'exp(x.*y).*(pi-2*(x.^2+y.^2))',...
        'grad_exact_1',     'y.*exp(x.*y)',...
        'grad_exact_2',     'x.*exp(x.*y)',...
        'alpha',             2,...
        'beta',              pi,...        
        'fem',              'P1',...         % Q1 - P1
        'nqn_1D',            4,...           % (1,2,3,4,5,6,.....)
        'nqn_2D',            3,...          % (1,3,4,7,10,16,64)
        'MeshType',         'TU', ...        % ['TS' 'TU' 'QS' 'QU']
        'refinement_vector', [3,4,5,6],...   % [0,1,2,3,4,5,6,7,....]
        'visual_graph',      'Y',...
        'print_out',         'Y',...
        'plot_errors',       'Y');

elseif test=='Test2'
        DATI= struct(  'name',  test,...
        'domain',           [0,1;0,1],...
        'exact_sol',        'exp(x.*y)',...
        'force',            'exp(x.*y).*(pi-2*(x.^2+y.^2))',...
        'grad_exact_1',     'y.*exp(x.*y)',...
        'grad_exact_2',     'x.*exp(x.*y)',...
        'alpha',             2,...
        'beta',              pi,...        
        'fem',              'P1',...         % Q1 - P1
        'nqn_1D',            4,...           % (1,2,3,4,5,6,.....)
        'nqn_2D',            3,...          % (1,3,4,7,10,16,64)
        'MeshType',         'TU', ...        % ['TS' 'TU' 'QS' 'QU']
        'refinement_vector', [3,4,5,6],...   % [0,1,2,3,4,5,6,7,....]
        'visual_graph',      'N',...
        'print_out',         'Y',...
        'plot_errors',       'Y');
end

 

